require "^.utils.__terminal";
require "labelstrings";
require "__windows_gui";
structure LabelStrings_ : LABELSTRINGS =
struct
type word = WindowsGui.word
type AcceleratorFlag = WindowsGui.accelerator_flag
val VK_F1 = 0x70
val VK_F2 = 0x71
val VK_F3 = 0x72
val VK_F4 = 0x73
val VK_F5 = 0x74
val VK_F6 = 0x75
val VK_F7 = 0x76
val VK_F8 = 0x77
val VK_F9 = 0x78
val VK_F10 = 0x79
val VK_F11 = 0x7a
val VK_F12 = 0x7b
val VK_TAB = 0x09
val VK_PRIOR = 0x21
val VK_NEXT = 0x22
val VK_END = 0x23
val VK_HOME = 0x24
val VK_LEFT = 0x25
val VK_UP = 0x26
val VK_RIGHT = 0x27
val VK_DOWN = 0x28
val VK_DELETE = 0x2e
val label_strings =
[
("personalAd", "About &Professional Edition"),
("mlwLicensing", "MLWorks &Licensing"),
("repeatButton", "Repeat"),
("editSourceButton", "Edit"),
("clear_messages", "Clear"),
("close_messages", "Close"),
("sysMessages", "S&ystem messages"),
("new_proj", "&New Project"),
("open_proj", "&Open Project"),
("save_proj", "&Save Project\tCtrl+S"),
("save_proj_as", "Save Project &As...\tCtrl+A"),
("load_proj_files", "&Load Project Files"),
("compile","&Compile Selection"),
("compile_all", "Compile &Target Sources"),
("load", "&Load Selection"),
("load_targets", "L&oad Targets"),
("recompile", "&Force Compile of Selection"),
("reload", "Force Load of &Selection"),
("check", "Read &Dependencies"),
("show", "Sho&w"),
("check_compile", "Files to &Compile Selection"),
("check_build", "Files to Compile &Target Sources"),
("check_load", "Files to &Load Selection"),
("check_targets", "Files to L&oad Targets"),
("proj_properties", "&Properties"),
("prop_files", "Common &Files"),
("prop_target", "&Targets"),
("prop_subproj", "&Subprojects"),
("prop_mode", "&Modes"),
("prop_config", "&Configurations"),
("prop_lib", "&Library path"),
("prop_obj_dir", "&Objects location"),
("prop_bin_dir", "&Binaries location"),
("prop_about", "&About"),
("PW_new", "New Project"),
("PW_open", "Open Project"),
("PW_choiceLabel", "Choose whether to create a new project or open an existing one:"),
("PW_readDependencies", "Read Dependencies"),
("PW_files", "Common Files"),
("PW_curTargets", "Targets"),
("PW_subprojects", "Subprojects"),
("PW_libraryPath", "Library Path"),
("PW_relativeBin", "Relative path names for Binaries"),
("PW_relativeObj", "Relative path names for Objects"),
("PW_objectsDir", "Objects Location"),
("PW_binariesDir", "Binaries Location"),
("projNameLabel", "Project Name: <NONE>"),
("projSourceLabel", "Project Source Path: "),
("projObjectsLabel", "Object Files Location: <NEED DEFAULT>"),
("projBinariesLabel", "Binary Files Location: <NEED DEFAULT>"),
("PWP_Ok", "OK"),
("PWP_Apply", "Apply"),
("PWP_Reset", "Reset"),
("PWP_Cancel", "Cancel"),
("PWP_files", "Relative path names"),
("PWP_config_files", "Relative path names"),
("PWP_config_lib", "Relative path names"),
("PWP_lib_path", "Relative path names"),
("PWP_propFilesLabel", "Files to be included in the project:"),
("PWP_moveUp", "Move Up"),
("PWP_moveDown", "Move Down"),
("PWP_removeSel", "Remove Selection"),
("PWP_removeAll", "Remove All"),
("PWP_addButton", "Add to List"),
("PWF_propFilesLabel", "Files to be included in the project:"),
("PWF_addFiles", "Add file(s)"),
("PWF_removeSel", "Remove Selection"),
("PWF_removeAll", "Remove All"),
("PWF_addButton", "Add From Directory"),
("PWT_addConfig","Set Configuration"),
("PWT_addMode", "Set Mode"),
("PWT_addTarget", "Add New Target"),
("PWT_configLabel", "Configuration:"),
("PWT_detailsLabel", "Details of selected current target:"),
("PWT_disable", "Disable"),
("PWT_disableLabel", "List of disabled target sources: "),
("PWT_dynlibRadio", "Dynamic Library"),
("PWT_enableTarget", "Enable"),
("PWT_exeRadio", "Executable"),
("PWT_imageRadio", "Image"),
("PWT_modeLabel", "Mode:"),
("PWT_moveDown", "Move Down"),
("PWT_moveUp", "Move Up"),
("PWT_objfileRadio", "Object File"),
("PWT_relative", "Relative path names"),
("PWT_removeDisabled", "Remove Selection"),
("PWT_removeTarget", "Remove Target"),
("PWT_typeLabel", "Target (destination) type:"),
("PWT_targetsLabel", "List of current target sources in build order:"),
("PWS_subprojLabel", "List of included subprojects:"),
("PWS_addProj", "Add"),
("PWS_removeProj", "Remove"),
("PWS_openProj", "Open"),
("PWS_backProj", "Back"),
("PWS_relProj", "Relative path names"),
("PWM_modeLabel", "List of modes:"),
("PWM_removeMode", "Remove Selected Mode"),
("PWM_setCurMode", "Set as Current"),
("PWM_addMode", "Add New Mode"),
("PWM_modeDetailsLabel", "Details of selected mode:"),
("PWM_locChange", "Set name of directory"),
("PWM_genInterruptCode", "Compile for interruptable loops"),
("PWM_genInterceptCode", "Compile for tracing and call-counting"),
("PWM_genDebugInfo", "Generate debug information"),
("PWM_genVarDebugInfo", "Generate variable debug information"),
("PWM_optLeaf", "Optimize leaf functions"),
("PWM_optTail", "Optimize tail calls"),
("PWM_optSelfTail", "Optimize self tail calls"),
("PWC_addBinLoc", "Set Binaries Location"),
("PWC_addConfig", "Add New Configuration"),
("PWC_configLabel", "List of configurations:"),
("PWC_files", "Files in Configuration"),
("PWC_libraryLabel", "Library path for selected configuration:"),
("PWC_libraryPath", "Set Library Path"),
("PWC_removeConfig", "Remove Selected Configuration"),
("PWC_setCurConfig", "Set As Current"),
("PWA_descLabel", "Project description:"),
("PWA_verLabel", "Project version information:"),
("expand_all", "&Expand All"),
("only_root", "Show Only &Root"),
("make_root", "&Make Selection Root"),
("original_root", "&Original Root"),
("layout_style", "&Layout Style"),
("cascading_layout", "&Cascading Layout"),
("tree_layout", "&Tree Layout"),
("indicate_hidden", "Indicate Hidden Children"),
("Cancel", "Exit MLWorks"),
("Help", "Cancel"),
("OK", "End GUI Session"),
("abandon", "&Abandon Current Definition"),
("abSyn","Abstract Syntax"),
("abandonButton","Abandon"),
("abort","&Abort"),
("abortButton","Abort"),
("abstractions","Abstractions"),
("action","&Action"),
("active","Linked"),
("addBreak", "Add Break Point"),
("addBreakTrace", "Add &Break/Trace Point"),
("addTrace", "Add Trace Point"),
("append","Append Selection"),
("apply","Apply"),
("autoSelection","&Auto-Update Tool"),
("backtrace", "Print &Backtrace"),
("barWidth","Bar width"),
("below","Below"),
("bottom","Bottom"),
("break","Breakpoint..."),
("breakTrace","&Break/Trace\tF10"),
("breakTraceButton", "Add Break/Trace Point"),
("breakTraceItem", "Name"),
("browseContext","Browse"),
("cancel","Cancel"),
("centre","Centre"),
("hcentre","Centre"),
("vcentre","Centre"),
("childPosition","Child Position"),
("clearButton","Clear"),
("clear_console","Clear Lo&g"),
("clear_def", "&Clear Current Definition"),
("close","&Close Window\tF4"),
("closeButton","Close"),
("compatibility","C&ompatibility..."),
("compatibilityMode","Compatibility"),
("compatibilityOptionsLabel","Compatibility Preferences"),
("compiler","&Compiler..."),
("compilerOptionsLabel","Compiler Preferences"),
("completionMenu","Use completion menu"),
("console","Log/Console"),
("content_type","Type"),
("content_value","Value"),
("context","&Context"),
("contextSelect","Select"),
("contextBrowser","&Context Browser\tF7"),
("contextWindow","&History\tF9"),
("continue","&Continue"),
("continueButton","Continue"),
("copy","&Copy\tCtrl+C"),
("current","Current"),
("custom_editor_name","Custom Editor Name"),
("cut","Cu&t\tCtrl+X"),
("debug_menu", "&Debug"),
("debuggerArgsLabel","Local Variables"),
("debuggerFramesLabel","Stack (grows upwards)"),
("debugging","Debugging"),
("defaultOverloads","Default types for overloaded operators"),
("default_visibility","Expand all children"),
("delete","&Delete Selection\tDel"),
("deleteAll","Delete &All"),
("deleteAllButton","Delete All Items"),
("deleteSelection","Remo&ve Selected Unit"),
("deleteSelectedButton","Remove Selected Item"),
("dismiss","Dismiss"),
("displayEntryTypes","Display Types of Entries"),
("duplicate","&Duplicate Tool"),
("edit","&Edit"),
("editButton","Edit"),
("editSource", "&Edit Source"),
("edit_error","Edit E&rror"),
("edit_frame","&Edit"),
("editor","&Editor..."),
("editorOptionsLabel","Editor Preferences"),
("editSelection","&Edit Selection"),
("environment","&General..."),
("environmentOptionsLabel","Miscellaneous Preferences"),
("eof","EOF"),
("error","E&rror"),
("errorTextLabel","Details"),
("evaluate", "&Evaluate"),
("evaluateButton","Evaluate"),
("exit","E&xit\tAlt+F4"),
("extensions","&Extensions..."),
("extensionsOptionsLabel","Extensions Preferences"),
("external_editor_command","External Editor Command"),
("file","&File"),
("fileBrowser","&File Tool"),
("filter","&Browser Filters..."),
("filterFrames","Debugger &Filters..."),
("fixitySpecs","Fixity directives in signatures"),
("floatPrecision","Precision of reals "),
("functionStepper","Function Stepper"),
("functor","Functor"),
("functors","Functors"),
("general", "&General Preferences"),
("generateDebugInfo","Generate debug information"),
("generateInterceptableCode","Compile for tracing and call-counting"),
("generateInterruptableCode","Compile for interruptible loops"),
("generateVariableDebugInfo","Generate variable debug information"),
("graph","&Graph Layout..."),
("graphLabel","Components"),
("graph_arity","Max. node arity"),
("graph_depth","Max. graph depth"),
("graph_seln_posn","Selection &Position..."),
("graph_sharing","Share equal values"),
("group","Group"),
("help_menu", "&Help"),
("hide","Hide"),
("hideAnonymousFrames","Hide anonymous frames"),
("hideCFrames","Hide C frames"),
("hideDeliveredFrames","Hide delivered frames"),
("hideHandlerFrames","Hide handler frames"),
("hideSetupFrames","Hide setup frames"),
("hideDuplicateFrames","Hide duplicate frames"),
("history","Hi&story"),
("historyTitleLabel","History"),
("horizontal","Horizontal"),
("horizontalSelection","Horizontal Selection"),
("horizontalSpacing","Horizontal"),
("idealLabelSpace","Ideal label spacing"),
("initialBrowser","&System Browser\tF8"),
("initialContext","New"),
("input","Input"),
("inputLabel","New input"),
("inputTitleLabel","Program"),
("insert","Insert Selection"),
("insp_item","In&spector..."),
("inspect","&Inspect"),
("inspectFrameInfo","&Inspect"),
("inspector","Inspector"),
("installationHelp", "&Installation"),
("internals","In&ternals..."),
("internalsOptionsLabel","Internals Options"),
("interruptButton","Interrupt"),
("intervalStepper","Interval Stepper"),
("itemSearch","Search for Item"),
("label","Messages"),
("labelOffset","Offset"),
("lambda","Lambda Code"),
("lambdaEnv","Lambda Environment"),
("language","&Language..."),
("layout","&Profiler Layout..."),
("left","Left"),
("lineStyle","Line Style:"),
("listLabel","Files:"),
("listener","&Listener\tF5"),
("listener_menu", "&Listener"),
("listen_props", "P&roperties"),
("local","Local"),
("make","Make"),
("makefull","Make..."),
("main","&Main"),
("maximumBars","Maximum number of bars"),
("maximumBreaks", "No. of breakpoints to skip"),
("maximumDepth","Maximum depth"),
("maximumHistoryLength","Maximum history length"),
("maximumNumberErrors","Maximum number of errors"),
("maximumRefDepth","Maximum ref depth"),
("maximumSeqSize","Maximum sequence size"),
("maximumStrDepth","Maximum structure depth"),
("maximumSigDepth","Maximum signature depth"),
("maximumStringSize","Maximum string size"),
("maximumTickSpace","Maximum tick spacing"),
("mipsR4000","Compile for MIPS R4000 and later"),
("mir","MIR Code"),
("mode","&Mode..."),
("modeOptionsLabel","Mode Preferences"),
("module","&Build"),
("moduleTitleLabel","Module"),
("moveto","Select"),
("next","&Next"),
("nextButton","Next"),
("next_def", "&Next Definition"),
("njSignatures","Limited `open' in signatures"),
("hnone","No Policy"),
("vnone","No Policy"),
("object","Object Code"),
("objectPath","Object Path"),
("ok","OK"),
("oldDefinition","SML 1990"),
("opInDatatype","`op' optional when unambiguous"),
("openFixity","Include fixity in `open'"),
("optLambda","Optimized Lambda Code"),
("optMir","Optimized MIR Code"),
("optimizeLeafFns","Optimize leaf functions"),
("optimizeSelfTailCalls","Optimize self tail calls"),
("optimizeTailCalls","Optimize tail calls"),
("optimizing","Optimizing"),
("options","&Details"),
("orientation","Orientation:"),
("origin","Origin"),
("horigin","Origin"),
("vorigin","Origin"),
("original","Original Root"),
("outputTitleLabel","Result"),
("parent","Parent"),
("paste","&Paste\tCtrl+V"),
("pathLabel","Source Path"),
("peel", "&Peel Off Function Profile"),
("peelButton","Peel Off"),
("popContext","Previous"),
("prevButton","Previous"),
("previousRoots","Previous Roots"),
("previous_def", "&Previous Definition"),
("profileButton","Profile"),
("profile", "Pro&file Evaluation"),
("project","Project"),
("project_menu", "&Project"),
("projWorkspace","&Project Workspace\tF6"),
("pushContext","Copy"),
("query","&Query"),
("quit","Quit"),
("read_depend","&Read Dependencies"),
("redo","&Redo"),
("referenceMan", "Reference &Manual"),
("releaseNotes", "&Release Notes"),
("removeAllBreakTrace", "Remove A&ll Break/Trace Points"),
("removeAllUnits", "Remove All &Units"),
("removeDuplicates","Remove D&uplicates"),
("removeUnit", "Remove Selected Unit"),
("repeat", "&Repeat Last Evaluation"),
("requireKeyword","`require' reserved word"),
("reset","Reset"),
("resultTitleLabel","Result"),
("right","Right"),
("roots","Roots"),
("save","Sa&ve Listener Input"),
("saveAs","Save Listener &Input As..."),
("saveImage","Sav&e Session As..."),
("savePreferences","&Save Preferences"),
("search","&Find..."),
("searchPervasives", "Search System Context"),
("searchUserContext","Search User Context"),
("select_emacs_server","Emacs Server"),
("select_vi","Vi"),
("select_external_editor","External"),
("select_custom_editor","Custom"),
("selectionLabel","Selection"),
("send","OK"),
("senseContext","Sense Context"),
("senseSelection","Sense Selection"),
("sensitivity","Sensitivity..."),
("sensitivityOptionsLabel","Sensitivity Options"),
("setBreakpoint","Enter Function Name:"),
("setBreakpointDialog","Set breakpoint"),
("setContext","Set Context"),
("setSelection","Set Selection"),
("setObjectPath","&Object Path..."),
("setWD","Current &Directory..."),
("settings","&Settings"),
("setup","P&references"),
("showAbsyn","Show abstract syntax"),
("showDebugInfo","Show debug info"),
("showEnviron","Show lambda environment"),
("showEqInfo","Show equality info"),
("showExnDetails","Show exception details"),
("showFnDetails","Show function details"),
("showFrameInfo","&Information..."),
("show_graph","&Dependencies of Selection"),
("show_defn","&View Source"),
("showIdClass","Show identifier class"),
("showLambda","Show lambda code"),
("showMach","Show object code"),
("showMir","Show MIR code"),
("showOptLambda","Show optimized lambda code"),
("showOptMir","Show optimized MIR code"),
("showVariableDebugInfo","Show variable info"),
("show_all","Expand all children"),
("show_atoms","Show atomic entries"),
("show_conenvs","Show constructor environments"),
("show_cons","Show constructors"),
("show_exns","Show exceptions"),
("show_funs","Show functors"),
("show_sigs","Show signatures"),
("show_strs","Show structures"),
("show_types","Show types"),
("show_vars","Show variables"),
("signature","Signature"),
("signatures","Signatures"),
("slider","Slider"),
("sml_90","SML '90"),
("sml_97","SML '97"),
("sort","S&ort"),
("sourcepath","Source Path"),
("sourceTitleLabel","Source"),
("spaceButton","Space"),
("sparcV7","Compile for SPARC V7"),
("srcTitleLabel","Source"),
("step","&Step"),
("stepButton","Step"),
("stepEval", "&Step Evaluation"),
("straight","Straight"),
("structure","Structure"),
("time", "&Time Evaluation"),
("timeButton","Time"),
("toggleMode","Toggle Mode"),
("tools","&Tools"),
("tool_settings", "&Tool Settings"),
("top","Top"),
("topLevel","Top Level"),
("toplevel","Top Level"),
("trace","&Trace"),
("typeCheck","Type Check"),
("typeDynamic","Type `&dynamic'"),
("typeTitleLabel","Type"),
("unit","Unit"),
("undo","Undo"),
("untrace","&Untrace"),
("update","Update"),
("usage_menu", "&Usage"),
("use","&Read Into Listener..."),
("useDebugger","Use debugger"),
("useErrorBrowser","Use error browser"),
("useRelativePathname","Relative pathnames in use"),
("userGuide", "&User Guide"),
("valTitleLabel","Value"),
("value","&Action"),
("valuePrinterOptionsLabel","Value Printer Options"),
("valueprinter","&Value Printer..."),
("vertical","Vertical"),
("verticalSelection","Vertical Selection"),
("verticalSpacing","Vertical"),
("view","&View"),
("visible","Visible"),
("weakTyvars","Weak type variables"),
("window","Window"),
("windowDebugger","Always use window debugger"),
("windows","&Windows")]
val accelerator_list =
[("previous_def",[WindowsGui.FALT,WindowsGui.FVIRTKEY],ord #"P"),
("next_def",[WindowsGui.FALT,WindowsGui.FVIRTKEY],ord #"N"),
("cut",[WindowsGui.FCONTROL,WindowsGui.FVIRTKEY],ord #"X"),
("copy",[WindowsGui.FCONTROL,WindowsGui.FVIRTKEY],ord #"C"),
("paste",[WindowsGui.FCONTROL,WindowsGui.FVIRTKEY],ord #"V"),
("save_proj",[WindowsGui.FCONTROL,WindowsGui.FVIRTKEY],ord #"S"),
("save_proj_as",[WindowsGui.FCONTROL,WindowsGui.FVIRTKEY],ord #"A"),
("close", [WindowsGui.FVIRTKEY],VK_F4),
("listener", [WindowsGui.FVIRTKEY], VK_F5),
("projWorkspace", [WindowsGui.FVIRTKEY], VK_F6),
("contextBrowser", [WindowsGui.FVIRTKEY], VK_F7),
("initialBrowser", [WindowsGui.FVIRTKEY], VK_F8),
("contextWindow", [WindowsGui.FVIRTKEY], VK_F9),
("breakTrace", [WindowsGui.FVIRTKEY], VK_F10),
("exit",[WindowsGui.FALT,WindowsGui.FVIRTKEY],VK_F4),
("close",[WindowsGui.FCONTROL,WindowsGui.FVIRTKEY],VK_F4)]
val title_list =
[("breakpointManager","Breakpoint Manager"),
("traceManager","Trace Manager"),
("quitDialog","MLWorks Exit Dialog"),
("messageDialog","Message"),
("completions","Completions"),
("searchList","Matches"),
("functionProfile","Function Profile")]
val label_actions =
map (fn (name,_) => (name,WindowsGui.newControlId ())) label_strings
exception LookupFailed
fun lookup (name,[]) = raise LookupFailed
| lookup (name,(name',id)::rest) =
if name = name' then id else lookup (name,rest)
fun get_title s =
lookup (s,title_list) handle LookupFailed => s
val accelerators =
map
(fn (label,flags,key) => (flags,key,WindowsGui.wordToInt (lookup (label,label_actions))))
accelerator_list
fun get_label name =
let
fun aux [] = name
| aux ((name',label)::rest) =
if name = name' then label
else aux rest
in
aux label_strings
end
fun get_action name =
let
fun aux [] = (Terminal.output("No action id for " ^ name ^ "\n");
WindowsGui.newControlId ())
| aux ((name',id)::rest) =
if name = name'
then id
else aux rest
in
aux label_actions
end
end
;
