package hello;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.OverrunStyle;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
public class HelloLabel extends Application {
static HBox wrapHBoxAroundLabel(Label label) {
HBox hbox = new HBox();
hbox.setId("hbox");
hbox.getChildren().add(new Rectangle(10,10, Color.BLACK));
label.setId(label.getText() != null? label.getText() : "no text");
hbox.getChildren().add(label);
hbox.getChildren().add(new Rectangle(12,12));
return hbox;
}
public static void main(String[] args) {
Application.launch(args);
}
@Override public void start(Stage stage) {
stage.setTitle("Hello Label");
VBox vbox = new VBox();
vbox.setId("vbox");
vbox.setSpacing(8);
vbox.getStyleClass().add("hellovlabel-vbox");
Scene scene = new Scene(vbox, 280,480);
Label label = new Label("Text");
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label();
label.setGraphic(new Circle(12));
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label(" and Text");
label.setId(label.getText());
label.setGraphic(new Circle(12));
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label("textWrap == true but shouldn't wrap");
label.setId(label.getText());
label.setWrapText(true);
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label("textWrap == true and prefwidth == 50 so should wrap and let's make this really really really long");
label.setId(label.getText());
label.setWrapText(true);
label.setPrefSize(50,70);
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label("textOverrun == CLIP");
label.setId(label.getText());
label.setTextOverrun(OverrunStyle.CLIP);
label.setPrefWidth(60);
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label("textOverrun == CENTER_ELLIPSIS");
label.setId(label.getText());
label.setTextOverrun(OverrunStyle.CENTER_ELLIPSIS);
label.setPrefWidth(60);
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label("textOverrun == CENTER_WORD_ELLIPSIS");
label.setId(label.getText());
label.setTextOverrun(OverrunStyle.CENTER_WORD_ELLIPSIS);
label.setPrefWidth(60);
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label("textOverrun == ELLIPSIS");
label.setId(label.getText());
label.setTextOverrun(OverrunStyle.ELLIPSIS);
label.setPrefWidth(60);
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label("textOverrun == LEADING ELLIPSIS");
label.setId(label.getText());
label.setTextOverrun(OverrunStyle.LEADING_ELLIPSIS);
label.setPrefWidth(60);
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label("textOverrun == LEADING WORD ELLIPSIS");
label.setId(label.getText());
label.setTextOverrun(OverrunStyle.LEADING_WORD_ELLIPSIS);
label.setPrefWidth(60);
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label("textOverrun == WORD_ELLIPSIS");
label.setId(label.getText());
label.setTextOverrun(OverrunStyle.WORD_ELLIPSIS);
label.setPrefWidth(60);
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label("line one.\nno spacing.");
vbox.getChildren().add(wrapHBoxAroundLabel(label));
label = new Label("line one.\nspacing please.");
label.setLineSpacing(10);
vbox.getChildren().add(wrapHBoxAroundLabel(label));
scene.setRoot(vbox);
stage.setScene(scene);
stage.show();
}
}
