package com.sun.javafx.menu;
import javafx.beans.property.BooleanProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.StringProperty;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.input.KeyCombination;
import javafx.scene.Node;
public interface MenuItemBase {
public void setId(String value);
public String getId();
public StringProperty idProperty();
public void setText(String value);
public String getText();
public StringProperty textProperty();
public void setGraphic(Node value);
public Node getGraphic();
public ObjectProperty<Node> graphicProperty();
public void setOnAction(EventHandler<ActionEvent> value);
public EventHandler<ActionEvent> getOnAction();
public ObjectProperty<EventHandler<ActionEvent>> onActionProperty();
public void setDisable(boolean value);
public boolean isDisable();
public BooleanProperty disableProperty();
public void setVisible(boolean value);
public boolean isVisible();
public BooleanProperty visibleProperty();
public void setAccelerator(KeyCombination value);
public KeyCombination getAccelerator();
public ObjectProperty<KeyCombination> acceleratorProperty();
public void setMnemonicParsing(boolean value);
public boolean isMnemonicParsing();
public BooleanProperty mnemonicParsingProperty();
public void fire();
public void fireValidation();
}
