package uk.ac.rhul.cs.csle.art.cfg.referenceFamily.grammar;

public enum LKind {
  CHARACTER, SINGLETON_CASE_SENSITIVE, SINGLETON_CASE_INSENSITIVE, ID, INTEGER, SIGNED_INTEGER, REAL, SIGNED_REAL, CHAR_BQ, STRING_SQ, STRING_DQ, STRING_PLAIN_SQ, STRING_BRACE_NEST, STRING_BRACKET_NEST, STRING_DOLLAR, SIMPLE_WHITESPACE, COMMENT_LINE_C, COMMENT_BLOCK_C, COMMENT_NEST_ART
}
